sudo: false
dist: precise
language: php
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - language-pack-fr
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - make clean
  - make check_permissions
  - make all_tests
