sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - make clean
  - make check_permissions
  - make test
