sudo: false
dist: trusty
language: php
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install:
  - composer self-update
  - composer install --prefer-dist
script:
  - locale -a
  - make clean
  - make check_permissions
  - make all_tests
