sudo: false
dist: trusty
language: php
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
install:
  - yarn install
  - composer install --prefer-dist
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
script:
  - make clean
  - make check_permissions
  - make eslint
  - make all_tests
