dist: bionic

matrix:
  include:
    # jobs for each supported php version
    - language: php
      php: 7.4
    - language: php
      php: 7.3
    - language: php
      php: 7.2
    - language: php
      php: 7.1
    # jobs for frontend builds
    - language: node_js
      node_js: 8
      cache:
        yarn: true
        directories:
          - $HOME/.cache/yarn
      install:
        - yarn install
      before_script:
        - PATH=${PATH//:\.\/node_modules\/\.bin/}
      script:
        - yarn run build # verify successful frontend builds
        - make eslint # javascript static analysis
        - make sasslint # linter for SASS syntax
    # jobs for documentation builds
    - language: python
      python: 3.6
      cache:
        directories:
          - $HOME/.cache/pip
      install:
        - pip install mkdocs
      script:
        - mkdocs build --clean

cache:
  directories:
    - $HOME/.composer/cache

install:
  # install/update composer and php dependencies
  - composer install --prefer-dist

before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}

script:
  - make clean
  - make check_permissions
  - make all_tests
