name: Build/push Docker image (tags/releases)
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "v*.*"
      - release
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "REF=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: |
            ${{ secrets.DOCKER_IMAGE }}:${{ env.REF }}
            ghcr.io/${{ secrets.DOCKER_IMAGE }}:${{ env.REF }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
