language: python
python:
  - "2.7"
install:
 - pip install -r requirements.txt
script:
 - python -m pytest src/Test --cov src --cov-config src/Test/coverage.ini
before_install:
  - pip install codecov
  - pip install pytest-cov
  - pip install coveralls
after_success:
  - codecov
  - coveralls
