language: python
python:
  - 2.7
install:
 - pip install -U pip wheel
 - pip install -r requirements.txt
before_script:
  - openssl version -a
script:
 - python -m pytest plugins/CryptMessage/Test
 - python -m pytest src/Test --cov=src --cov-config src/Test/coverage.ini
before_install:
  - pip install -U pytest mock pytest-cov
  - pip install codecov
  - pip install coveralls
after_success:
  - codecov
  - coveralls --rcfile=src/Test/coverage.ini
cache:
  directories:
    - $HOME/.cache/pip